language: node_js
node_js:
- '8'
before_install:
- openssl aes-256-cbc -K $encrypted_7410759ccf67_key -iv $encrypted_7410759ccf67_iv -in deploy-creds.tar.enc -out deploy-creds.tar -d
- tar xvf deploy-creds.tar
- wget https://github.com/gohugoio/hugo/releases/download/v0.33/hugo_0.33_Linux-64bit.deb
- sudo dpkg -i hugo_0.33_Linux-64bit.deb
- rm *.deb
script: node --max-old-space-size=4096 compile.js -b $TRAVIS_BRANCH
before_script:
- mkdir dist
cache:
  npm: false
before_deploy:
  - 'curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "awscli-bundle.zip"'
  - 'unzip awscli-bundle.zip'
  - './awscli-bundle/install -b ~/bin/aws'
  - 'cd web; if [ "$TRAVIS_BRANCH" = "stage" ] ; then sed -i -e "s/sabbath-school\.adventech\.io/sabbath-school-stage\.adventech\.io/g" config.toml; fi'
  - 'hugo -DF'
  - 'cd .. && mv -v web/public/* dist/'
deploy:
  - provider: script
    skip_cleanup: true
    script: aws s3 sync dist/ s3://sabbath-school-stage.adventech.io --acl "public-read" --region us-east-1 --no-progress --size-only
    on:
      branch: stage
  - provider: script
    skip_cleanup: true
    script: aws s3 sync dist/ s3://sabbath-school.adventech.io --acl "public-read" --region us-east-1 --no-progress --size-only
    on:
      branch: master
env:
  global:
  - secure: ZetrKtuVC6+fF57g+o0nq2t4nckuXTzlO33jNYo70PAYnwzeVfDImcVebmyhbGx8zAu8PIwh/YVCD+BVm4yTQpEk5ldWU1f6YD6B2hCtT8KKmeIBSCRl2EwK9uJfzLW2hXmULjLi8Vyfj02hR35QqxhT2dtcnSQJxXwBeHBhBN+Z6wLxshbMz2WaLZPXHMYP4k6khXNCNMcqdMkQjBPREX+R18wuKKKgxHHZRHmZbhXV23afQvpLceW32TO+XbN98VLFgFj2dDod3LAbr3UO3QDnO6JQDTsb01gf5Towxl+4yvLiSVbz9FEjxosjPZ12of/FixR9iLGeZcmD+TRTMrXR94lPrczdezn0RSBG8uvZbXbnVsk8C0bFUlUiyZyo5SdulYvbUCGUGFB++g01xd3L4nCWQDKf2aISQ6mGze6LESH9kr+9P7GJ8I+qMmnZWBu3Zju1lDaZDqMuHTLPJqUgDi2OpIe+9y/2FpOr3fgPq/OBoEhwuDODifuXx3fZdmaoFoadbWJbs4Ey85iirpQxhZ7s/5bVvFx3/vAdtrihLgtzZ3UuZi85GmXVImDCqFxAFOdgQaurSs7+coxQJ7UndwRIy+lp8iTsThXAj+ukV5CChFwMUytogchyJCJSET7sqq0qzCMQNw0YSWTxH1UrCRlmjTBwvI42rYqQey8=
  - secure: ZXITlidXIumuagGvAL40jnls8E3ga7+OR9CfoQtnZ6W1Kadfvcerw9XE58qFHlY1q5WddgYKnoCX/jOMUrCd4COc/oBVzhk5PcORqc+cK4tklZjg6eqNjQpEGgZTEXuNB8HrEu46n3SYY6KUT0Q41W3uQNGa2jGj6HO/J0zsjBfXr8jFIl9H18IisiYmrhlyiV6qhiD4BWypGrW0nHf1OPilYIV5K2K++NEEF2FhrG/QyHwDQQN+0XKINpCap/KHYQLUB/JNcsFBtVEM9qvUwE0iSf1p2UdlbRUGDhuDeGM+uImbKQk/f/ae2zcTvTzvc1vYXO6l2YMX4sOu0uHV5BDnEmgVJpwmOsMcpGaHO9Rp3S70wFsot9kMrbfbYUJ0711ZDhKCNIKMvPDQisPrRClZYUf2JCrkL4KZQTTeB7USr0UP8OpNEHPHYv73wciRCcJ3E27iGiuEUqZ2iYQUz94WwNtUZ73MJtxpzkwcLUd1FqiyQSFRJJzIm5+kDpaDIlKvGdktnwlgYyUJUBy2w5IHeAWTh3gIpyzjpzsEObWj0j/3yQuPnhX05JsjelfMHnGmzpRLauY5sktVMkJrKecqfOkCjnBjR49vsI83XCYC9SCyEJqnKzBCBVRVkQebuGLcv3oEOJCHA2G9z3sembKJ4xdCIHBy/XLja8YksVc=
