baseURL = "https://sabbath-school.adventech.io/"
languageCode = "en"
title = "Sabbath School"

# very ugly, but quicker way to implement i18n using config
[params]
[params.en]
	title = "Sabbath School"
	back = "Go back"
	all = "See all"
	todaysLesson = "Today's Lesson"
	current = "Current"
	archive = "Lesson archive"
	lang = "ğŸ‡ºğŸ‡¸ English"

[params.ar]
	title = "Ù…Ø¯Ø±Ø³Ø© Ø§Ù„Ø³Ø¨Øª"
	back = "Ø¹ÙØ¯"
	all = "Ø§Ø¸Ù‡Ø§Ø± Ø§Ù„ÙƒÙ„"
	todaysLesson = "Ø¯Ø±Ø³ Ø§Ù„ÙŠÙˆÙ…"
	current = "ØªÙŠØ§Ø±"
	archive = "Ø£Ø±Ø´ÙŠÙ Ø§Ù„Ø¯Ø±Ø³"
	lang = "ğŸ‡¸ğŸ‡¦ Ø¹Ø±Ø¨Ù‰"

[params.bg]
	title = "Ğ¡ÑŠĞ±Ğ¾Ñ‚Ğ½Ğ¾ Ğ£Ñ‡Ğ¸Ğ»Ğ¸Ñ‰Ğµ"
	back = "Ğ’ÑŠÑ€Ğ½Ğ¸ ÑĞµ"
	all = "Ğ’Ğ¸Ğ¶ Ğ²ÑĞ¸Ñ‡ĞºĞ¸"
	todaysLesson = "Ğ”Ğ½ĞµÑˆĞ½Ğ¸ÑÑ‚ ÑƒÑ€Ğ¾Ğº"
	current = "Ğ¢ĞµĞºÑƒÑ‰"
	archive = "Ğ’Ğ¸Ğ¶ Ğ²ÑĞ¸Ñ‡ĞºĞ¸"
	lang = "ğŸ‡§ğŸ‡¬ Ğ‘ÑŠĞ»Ğ³Ğ°Ñ€ÑĞºĞ¸"

[params.zh]
	title = "å®‰æ¯æ—¥å­¦"
	back = "å›å»"
	all = "æŸ¥çœ‹å…¨éƒ¨"
	todaysLesson = "ä»Šå¤©çš„è¯¾ç¨‹"
	current = "å½“å‰"
	archive = "è¯¾ç¨‹æ¡£æ¡ˆ"
	lang = "ğŸ‡¨ğŸ‡³ ä¸­æ–‡"

[params.da]
	title = "Sabbatsskole"
	back = "GÃ¥ tilbage"
	all = "Se alt"
	todaysLesson = "Dagens lektion"
	current = "NuvÃ¦rende"
	archive = "Lektion arkiv"
	lang = "ğŸ‡©ğŸ‡° Dansk"

[params.fr]
	title = "Ã‰cole du Sabbat"
	back = "Retourner"
	all = "Voir tout"
	todaysLesson = "LeÃ§on d'aujourd'hui"
	current = "Actuel"
	archive = "Archive des leÃ§ons"
	lang = "ğŸ‡«ğŸ‡· FranÃ§ais"

[params.de]
	title = "Sabbatschule"
	back = "Geh zurÃ¼ck"
	all = "Alles sehen"
	todaysLesson = "Die heutige Lektion"
	current = "Strom"
	archive = "Unterrichtsarchiv"
	lang = "ğŸ‡©ğŸ‡ª Deutsche"

[params.in]
	title = "Sekolah Sabat"
	back = "Kembali"
	all = "Lihat semua"
	todaysLesson = "Pelajaran hari ini"
	current = "Saat ini"
	archive = "Arsip pelajaran"
	lang = "ğŸ‡®ğŸ‡© Bahasa Indonesia"

[params.ja]
	title = "å®‰æ¯æ—¥å­¦æ ¡"
	back = "æˆ»ã‚‹"
	all = "ã™ã¹ã¦ã‚’è¦‹ã‚‹"
	todaysLesson = "ä»Šæ—¥ã®èª²"
	current = "ç¾åœ¨"
	archive = "èª²ã®ã‚¢ãƒ¼ã‚«ã‚¤ãƒ–"
	lang = "ğŸ‡¯ğŸ‡µ æ—¥æœ¬èª"

[params.ko]
	title = "ì•ˆì‹ì¼ í•™êµ"
	back = "ëŒì•„ ê°€ê¸°"
	all = "ëª¨ë‘ë³´ê¸°"
	todaysLesson = "ì˜¤ëŠ˜ì˜ ìˆ˜ì—…"
	current = "íë¦„"
	archive = "ê°•ì˜ ì•„ì¹´ì´ë¸Œ"
	lang = "ğŸ‡°ğŸ‡· í•œêµ­ì–´"

[params.ms]
	title = "Sekolah Sabat"
	back = "Pergi balik"
	all = "Lihat semua"
	todaysLesson = "Pelajaran Hari Ini"
	current = "Semasa"
	archive = "Arkib pelajaran"
	lang = "ğŸ‡²ğŸ‡¾ Bahasa Melayu"

[params.no]
	title = "Sabbatsskole"
	back = "GÃ¥ tilbake"
	all = "Se alt"
	todaysLesson = "Dagens leksjon"
	current = "NÃ¥vÃ¦rende"
	archive = "Leksjonsarkiv"
	lang = "ğŸ‡³ğŸ‡´ Norsk"

[params.fa]
	title = "Ù…Ø¯Ø±Ø³Ù‡ Ø³Ø¨Øª"
	back = "Ø¨Ø±Ú¯Ø±Ø¯"
	all = "Ù‡Ù…Ù‡ Ø±Ø§ Ø¨Ø¨ÛŒÙ†"
	todaysLesson = "Ø¯Ø±Ø³ Ø§Ù…Ø±ÙˆØ²"
	current = "Ø¬Ø§Ø±ÛŒ"
	archive = "Ø¢Ø±Ø´ÛŒÙˆ Ø¯Ø±Ø³"
	lang = "ğŸ‡®ğŸ‡· ÙØ§Ø±Ø³ÛŒ"

[params.ro]
	title = "È˜coala de Sabat"
	back = "Ãntoarce-te"
	all = "Vezi toate"
	todaysLesson = "LecÈ›ia de astÄƒzi"
	current = "Actual"
	archive = "Arhiva lecÈ›iilor"
	lang = "ğŸ‡·ğŸ‡´ RomÃ¢nÄƒ"

[params.ru]
	title = "Ğ¡ÑƒĞ±Ğ±Ğ¾Ñ‚Ğ½ÑÑ Ğ¨ĞºĞ¾Ğ»Ğ°"
	back = "ĞĞ°Ğ·Ğ°Ğ´"
	all = "Ğ’ÑĞµ ÑƒÑ€Ğ¾ĞºĞ¸"
	todaysLesson = "Ğ¡ĞµĞ³Ğ¾Ğ´Ğ½ÑÑˆĞ½Ğ¸Ğ¹ ÑƒÑ€Ğ¾Ğº"
	current = "Ğ¢ĞµĞºÑƒÑ‰Ğ¸Ğ¹"
	archive = "ĞÑ€Ñ…Ğ¸Ğ² ÑƒÑ€Ğ¾ĞºĞ¾Ğ²"
	lang = "ğŸ‡·ğŸ‡º Ğ ÑƒÑÑĞºĞ¸Ğ¹"

[params.sr]
	title = "Subotna Å¡kola"
	back = "Vratiti se"
	all = "Sve lekcije"
	todaysLesson = "DanaÅ¡nja lekcija"
	current = "Trenutni"
	archive = "Lekcije Arhiva"
	lang = "ğŸ‡·ğŸ‡¸ Srpski"

[params.es]
	title = "Escuela SabÃ¡tica"
	back = "Regresa"
	all = "Ver todo"
	todaysLesson = "La lecciÃ³n de hoy"
	current = "Corriente"
	archive = "Archivo de la lecciÃ³n"
	lang = "ğŸ‡ªğŸ‡¸ EspaÃ±ol"

[params.tr]
	title = "Sebt Okulu"
	back = "Geri dÃ¶n"
	all = "Hepsini gÃ¶r"
	todaysLesson = "BugÃ¼nÃ¼n dersi"
	current = "Åimdiki"
	archive = "Ders arÅŸivi"
	lang = "ğŸ‡¹ğŸ‡· TÃ¼rk"

[params.uk]
	title = "Ğ¡ÑƒĞ±Ğ¾Ñ‚Ğ½Ñ Ğ¨ĞºĞ¾Ğ»Ğ°"
	back = "ĞŸĞ¾Ğ²ĞµÑ€Ñ‚Ğ°Ğ¹ÑÑ"
	all = "Ğ‘Ğ°Ñ‡Ğ¸Ñ‚Ğ¸ Ğ²ÑĞµ"
	todaysLesson = "Ğ¡ÑŒĞ¾Ğ³Ğ¾Ğ´Ğ½Ñ–ÑˆĞ½Ñ–Ğ¹ ÑƒÑ€Ğ¾Ğº"
	current = "Ğ¡Ñ‚Ñ€ÑƒĞ¼"
	archive = "ĞÑ€Ñ…Ñ–Ğ² ÑƒÑ€Ğ¾ĞºÑƒ"
	lang = "ğŸ‡ºğŸ‡¦ Ğ£ĞºÑ€Ğ°Ñ—Ğ½ÑÑŒĞºĞ°"

[params.cs]
	title = "SobotnÃ­ Å¡kola"
	back = "ZadnÃ­"
	all = "VÅ¡echny lekce"
	todaysLesson = "DneÅ¡nÃ­ lekce"
	current = "AktuÃ¡lnÃ­"
	archive = "Archiv hodin"
	lang = "ğŸ‡¨ğŸ‡¿ ÄŒesky"

[params.he]
	title = "×¡×¤×¨ ×©×‘×ª"
	back = "×ª×—×–×•×¨"
	all = "×›×œ ×”×©×™×¢×•×¨×™×"
	todaysLesson = "×”×©×™×¢×•×¨ ×©×œ ×”×™×•×"
	current = "× ×•Ö¹×›Ö°×—Ö´×™"
	archive = "××¨×›×™×•×Ÿ ×”×©×™×¢×•×¨"
	lang = "ğŸ‡®ğŸ‡± ×¢Ö´×‘×¨Ö´×™×ª"

[params.ne]
	title = "à¤¸à¤¬à¥à¤¬à¤¾à¤¥ à¤¸à¥à¤•à¥‚à¤²"
	back = "à¤ªà¤›à¤¾à¤¡à¥€ à¤œà¤¾à¤‰"
	all = "à¤¸à¤¬à¥ˆ à¤ªà¤¾à¤ à¤¹à¤°à¥‚ à¤¹à¥‡à¤°à¥à¤¨à¥à¤¹à¥‹à¤¸à¥"
	todaysLesson = "à¤†à¤œà¤•à¥‹ à¤ªà¤¾à¤ "
	current = "à¤µà¤°à¥à¤¤à¤®à¤¾à¤¨"
	archive = "à¤ªà¤¾à¤  à¤¸à¤‚à¤—à¥à¤°à¤¹"
	lang = "ğŸ‡³ğŸ‡µ à¤¨à¥‡à¤ªà¤¾à¤²à¥€"

[params.mk]
	title = "Ğ¡Ğ°Ğ±Ğ°Ñ‚ Ğ£Ñ‡Ğ¸Ğ»Ğ¸ÑˆÑ‚Ğµ"
	back = "Ğ’Ñ€Ğ°Ñ‚Ğ¸ ÑĞµ Ğ½Ğ°Ğ·Ğ°Ğ´"
	all = "Ğ’Ğ¸Ğ´Ğ¸ Ğ³Ğ¸ ÑĞ¸Ñ‚Ğµ"
	todaysLesson = "Ğ›ĞµĞºÑ†Ğ¸Ñ˜Ğ° Ğ´ĞµĞ½ĞµÑ"
	current = "Ğ¢ĞµĞºĞ¾Ğ²Ğ½Ğ°"
	archive = "ĞÑ€Ñ…Ğ¸Ğ²Ğ° Ğ½Ğ° Ğ»ĞµĞºÑ†Ğ¸Ñ˜Ğ°"
	lang = "ğŸ‡²ğŸ‡° ĞœĞ°ĞºĞµĞ´Ğ¾Ğ½ÑĞºĞ¸"

[params.et]
	title = "HingamispÃ¤evakooli Ã•ppetÃ¼kk"
	back = "Mine tagasi"
	all = "KÃµik Ãµppetunnid"
	todaysLesson = "TÃ¤nane Ãµppetund"
	current = "Praegune kvartal"
	archive = "Ã•ppetundide arhiiv"
	lang = "ğŸ‡ªğŸ‡ª Eesti keel"

[params.fj]
	title = "Lesoni ni Wilivola Vakasigatabu"
	back = "Lesu tale"
	all = "Lesoni taucoko"
	todaysLesson = "Lesoni nikua"
	current = "Ena gauna oqo ni vulatolu"
	archive = "Akaivi ni lesoni"
	lang = "ğŸ‡«ğŸ‡¯ Viti"