baseURL = "https://sabbath-school.adventech.io/"
languageCode = "en"
title = "Sabbath School"

# very ugly, but quicker way to implement i18n using config
[params]
[params.en]
	title = "Sabbath School"
	back = "Go back"
	all = "See all"
	todaysLesson = "Today's Lesson"
	current = "Current"
	archive = "Lesson archive"
	lang = "ğŸ‡ºğŸ‡¸ English"

[params.ar]
	title = "Ù…Ø¯Ø±Ø³Ø© Ø§Ù„Ø³Ø¨Øª"
	back = "Ø¹ÙØ¯"
	all = "Ø§Ø¸Ù‡Ø§Ø± Ø§Ù„ÙƒÙ„"
	todaysLesson = "Today's Lesson"
	current = "Current"
	archive = "Ø£Ø±Ø´ÙŠÙ Ø§Ù„Ø¯Ø±Ø³"
	lang = "ğŸ‡¸ğŸ‡¦ Ø¹Ø±Ø¨Ù‰"

[params.bg]
	title = "Ğ¡ÑŠĞ±Ğ¾Ñ‚Ğ½Ğ¾ Ğ£Ñ‡Ğ¸Ğ»Ğ¸Ñ‰Ğµ"
	back = "Ğ’ÑŠÑ€Ğ½Ğ¸ ÑĞµ"
	all = "Ğ’Ğ¸Ğ¶ Ğ²ÑĞ¸Ñ‡ĞºĞ¸"
	todaysLesson = "Today's Lesson"
	current = "Current"
	archive = "Ğ’Ğ¸Ğ¶ Ğ²ÑĞ¸Ñ‡ĞºĞ¸"
	lang = "ğŸ‡§ğŸ‡¬ Ğ‘ÑŠĞ»Ğ³Ğ°Ñ€ÑĞºĞ¸"

[params.zh]
	title = "å®‰æ¯æ—¥å­¦"
	back = "å›å»"
	all = "æŸ¥çœ‹å…¨éƒ¨"
	todaysLesson = "Today's Lesson"
	current = "Current"
	archive = "è¯¾ç¨‹æ¡£æ¡ˆ"
	lang = "ğŸ‡¨ğŸ‡³ ä¸­æ–‡"

[params.da]
	title = "Sabbatsskole"
	back = "GÃ¥ tilbage"
	all = "Se alt"
	todaysLesson = "Today's Lesson"
	current = "Current"
	archive = "Lektion arkiv"
	lang = "ğŸ‡©ğŸ‡° Dansk"

[params.fr]
	title = "Ã‰cole du Sabbat"
	back = "Retourner"
	all = "Voir tout"
	todaysLesson = "Today's Lesson"
	current = "Current"
	archive = "Archive des leÃ§ons"
	lang = "ğŸ‡«ğŸ‡· FranÃ§ais"

[params.de]
	title = "Sabbatschule"
	back = "Geh zurÃ¼ck"
	all = "Alles sehen"
	todaysLesson = "Today's Lesson"
	current = "Current"
	archive = "Unterrichtsarchiv"
	lang = "ğŸ‡©ğŸ‡ª Deutsche"

[params.in]
	title = "Sekolah Sabat"
	back = "Kembali"
	all = "Lihat semua"
	todaysLesson = "Today's Lesson"
	current = "Current"
	archive = "Arsip pelajaran"
	lang = "ğŸ‡®ğŸ‡© Bahasa Indonesia"

[params.ja]
	title = "å®‰æ¯æ—¥å­¦æ ¡"
	back = "æˆ»ã‚‹"
	all = "ã™ã¹ã¦ã‚’è¦‹ã‚‹"
	todaysLesson = "Today's Lesson"
	current = "Current"
	archive = "ãƒ¬ãƒƒã‚¹ãƒ³ã‚¢ãƒ¼ã‚«ã‚¤ãƒ–"
	lang = "ğŸ‡¯ğŸ‡µ æ—¥æœ¬èª"

[params.ko]
	title = "ì•ˆì‹ì¼ í•™êµ"
	back = "ëŒì•„ ê°€ê¸°"
	all = "ëª¨ë‘ë³´ê¸°"
	todaysLesson = "Today's Lesson"
	current = "Current"
	archive = "ê°•ì˜ ì•„ì¹´ì´ë¸Œ"
	lang = "ğŸ‡°ğŸ‡· í•œêµ­ì–´"

[params.ms]
	title = "Sekolah Sabat"
	back = "Pergi balik"
	all = "Lihat semua"
	todaysLesson = "Today's Lesson"
	current = "Current"
	archive = "Arkib pelajaran"
	lang = "ğŸ‡²ğŸ‡¾ Bahasa Melayu"

[params.no]
	title = "Sabbatsskole"
	back = "GÃ¥ tilbake"
	all = "Se alt"
	todaysLesson = "Today's Lesson"
	current = "Current"
	archive = "Leksjonsarkiv"
	lang = "ğŸ‡³ğŸ‡´ Norsk"

[params.fa]
	title = "Ù…Ø¯Ø±Ø³Ù‡ Ø³Ø¨Øª"
	back = "Ø¨Ø±Ú¯Ø±Ø¯"
	all = "Ù‡Ù…Ù‡ Ø±Ø§ Ø¨Ø¨ÛŒÙ†"
	todaysLesson = "Today's Lesson"
	current = "Current"
	archive = "Ø¢Ø±Ø´ÛŒÙˆ Ø¯Ø±Ø³"
	lang = "ğŸ‡®ğŸ‡· ÙØ§Ø±Ø³ÛŒ"

[params.ro]
	title = "È˜coala de Sabat"
	back = "Ãntoarce-te"
	all = "Vezi toate"
	todaysLesson = "Today's Lesson"
	current = "Current"
	archive = "Arhiva lecÈ›iilor"
	lang = "ğŸ‡·ğŸ‡´ RomÃ¢nÄƒ"

[params.ru]
	title = "Ğ¡ÑƒĞ±Ğ±Ğ¾Ñ‚Ğ½ÑÑ Ğ¨ĞºĞ¾Ğ»Ğ°"
	back = "ĞĞ°Ğ·Ğ°Ğ´"
	all = "Ğ’ÑĞµ ÑƒÑ€Ğ¾ĞºĞ¸"
	todaysLesson = "Today's Lesson"
	current = "Current"
	archive = "ĞÑ€Ñ…Ğ¸Ğ² ÑƒÑ€Ğ¾ĞºĞ¾Ğ²"
	lang = "ğŸ‡·ğŸ‡º Ğ ÑƒÑÑĞºĞ¸Ğ¹"

[params.sr]
	title = "Subotna Å¡kola"
	back = "Vratiti se"
	all = "Sve lekcije"
	todaysLesson = "Today's Lesson"
	current = "Current"
	archive = "Lekcije Arhiva"
	lang = "ğŸ‡·ğŸ‡¸ Srpski"

[params.es]
	title = "Escuela SabÃ¡tica"
	back = "Regresa"
	all = "Ver todo"
	todaysLesson = "Today's Lesson"
	current = "Current"
	archive = "Archivo de la lecciÃ³n"
	lang = "ğŸ‡ªğŸ‡¸ EspaÃ±ol"

[params.tr]
	title = "Sebt Okulu"
	back = "Geri dÃ¶n"
	all = "Hepsini gÃ¶r"
	todaysLesson = "Today's Lesson"
	current = "Current"
	archive = "Ders arÅŸivi"
	lang = "ğŸ‡¹ğŸ‡· TÃ¼rk"

[params.uk]
	title = "Ğ¡ÑƒĞ±Ğ¾Ñ‚Ğ½Ñ Ğ¨ĞºĞ¾Ğ»Ğ°"
	back = "ĞŸĞ¾Ğ²ĞµÑ€Ñ‚Ğ°Ğ¹ÑÑ"
	all = "Ğ‘Ğ°Ñ‡Ğ¸Ñ‚Ğ¸ Ğ²ÑĞµ"
	todaysLesson = "Today's Lesson"
	current = "Current"
	archive = "ĞÑ€Ñ…Ñ–Ğ² ÑƒÑ€Ğ¾ĞºÑƒ"
	lang = "ğŸ‡ºğŸ‡¦ Ğ£ĞºÑ€Ğ°Ñ—Ğ½ÑÑŒĞºĞ°"

[params.cs]
	title = "SobotnÃ­ Å¡kola"
	back = "ZadnÃ­"
	all = "VÅ¡echny lekce"
	todaysLesson = "Today's Lesson"
	current = "Current"
	archive = "Archiv hodin"
	lang = "ğŸ‡¨ğŸ‡¿ ÄŒesky"

[params.he]
	title = "×¡×¤×¨ ×©×‘×ª"
	back = "×ª×—×–×•×¨"
	all = "×›×œ ×”×©×™×¢×•×¨×™×"
	todaysLesson = "Today's Lesson"
	current = "Current"
	archive = "××¨×›×™×•×Ÿ ×”×©×™×¢×•×¨"
	lang = "ğŸ‡®ğŸ‡± ×¢Ö´×‘×¨Ö´×™×ª"